// sitemap.xml and robots.txt (spec site-metadata; add-seo-and-sharing D6), generated by the
// playground build from the registry and SITE_ORIGIN, so that neither holds a hand-written copy of
// the origin or of the page list.

import { type PageMeta, SITE_ORIGIN } from './pages.ts';

const escapeXml = (text: string) =>
  text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');

/**
 * The canonical URL of every page, in registry order. There is no `lastmod`: the tree has no
 * truthful modification date per page, and file times or git history are not one.
 */
export function sitemapXml(pages: readonly PageMeta[]): string {
  const urls = pages.map((page) => `  <url><loc>${escapeXml(page.canonical)}</loc></url>`);
  return ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', ...urls, '</urlset>', ''].join('\n');
}

/** Every crawler may read every path; the 4D packs stay allowed, because rendering a world needs them. */
export function robotsTxt(): string {
  return ['User-agent: *', 'Allow: /', '', `Sitemap: ${SITE_ORIGIN}/sitemap.xml`, ''].join('\n');
}
